// This is a Statically Generated (SSG) component.
// In the Next.js App Router, components are statically generated by default.
// The data for this page will be fetched once at build time.
export default async function PostsPage() {
  // Fetch posts from the JSONPlaceholder API.
  // Since there are no caching options specified, Next.js will default
  // to `cache: 'force-cache'`, which means it fetches data at build time.
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  return (
    <main className="p-6 bg-gray-50 min-h-screen font-sans">
      <div className="max-w-2xl mx-auto bg-white p-6 rounded-lg shadow-md">
        <h1 className="text-2xl font-bold mb-4 text-gray-800">SSG Posts Example</h1>
        <ul className="space-y-3">
          {/* We slice the first 10 posts and map over them to render list items. */}
          {/* In JSX, we remove the TypeScript type annotation `: any` from the parameter `p`. */}
          {posts.slice(0, 10).map((p) => (
            <li key={p.id} className="p-3 bg-gray-100 rounded-md text-gray-700">
              {p.title}
            </li>
          ))}
        </ul>
      </div>
    </main>
  );
}
